#!/usr/bin/env python3
"""
Build script for DESPERATION (browser demake).

The ES6 modules under js/ are the single source of truth. This script produces
the two distributable artifacts from them:

  Desperation-singlefile.html   one self-contained file, opens by double-click
  desperation-web.zip           itch.io upload (modular build)

Usage (from the repo root):

    python tools/build.py

Requires nothing but a stock Python 3 install.

How the single-file build works: the modules are concatenated in dependency
order with their import/export statements stripped. Because every module's
top-level declarations then share one script scope -- which is exactly how this
codebase was originally written -- the result is byte-for-byte equivalent logic
with no bundler involved.
"""

import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Dependency order. Every module may only reference modules listed above it.
MODULES = [
    "js/utils.js",
    "js/config.js",
    "js/state.js",
    "js/audio.js",
    "js/gfx.js",
    "js/ui.js",
    "js/world.js",
    "js/entities/player.js",
    "js/entities/monster.js",
    "js/gameplay.js",
    "js/gameflow.js",
    "js/main.js",
]

ZIP_CONTENTS = ["index.html", "css/style.css"] + MODULES

IMPORT_RE = re.compile(r"^\s*import\s*\{[^}]*\}\s*from\s*['\"][^'\"]+['\"]\s*;?\s*$", re.M)
EXPORT_RE = re.compile(r"^\s*export\s*\{[^}]*\}\s*;?\s*$", re.M)


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return fh.read()


def write(rel, text):
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return len(text)


def strip_module_syntax(src, name):
    """Remove import/export statements so the file can live in a shared scope."""
    src = IMPORT_RE.sub("", src)
    src = EXPORT_RE.sub("", src)
    leftover = re.search(r"^\s*(import|export)\b", src, re.M)
    if leftover:
        line = src[: leftover.start()].count("\n") + 1
        sys.exit(
            f"error: {name}:{line} still contains module syntax the build cannot "
            f"strip. Keep imports/exports to the single-line `import{{a,b}}from'./x.js';` form."
        )
    return src.strip("\n")


def build_singlefile():
    chunks = []
    for rel in MODULES:
        body = strip_module_syntax(read(rel), rel)
        chunks.append(f"/* ===================== {rel} ===================== */\n{body}")
    bundle = "\n\n".join(chunks)

    html = read("index.html")
    css = read("css/style.css").strip()

    # NOTE: the replacements are passed as lambdas on purpose. A plain string
    # replacement would make re.subn interpret backslash escapes inside it, and
    # every "\n" in the game's JS string literals would turn into a real newline
    # -- silently producing unterminated strings.
    html, n = re.subn(
        r'<link rel="stylesheet" href="\./css/style\.css"\s*/?>',
        lambda m: "<style>\n" + css + "\n</style>",
        html,
    )
    if n != 1:
        sys.exit("error: could not find the stylesheet <link> in index.html")

    html, n = re.subn(
        r'<script type="module" src="\./js/main\.js"></script>',
        lambda m: '<script>\n"use strict";\n' + bundle + "\n</script>",
        html,
    )
    if n != 1:
        sys.exit("error: could not find the module <script> in index.html")

    banner = (
        "<!--\n"
        "  DESPERATION - single-file build.\n"
        "  GENERATED by tools/build.py - do not edit by hand; edit js/*.js and rebuild.\n"
        "-->\n"
    )
    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)
    return write("Desperation-singlefile.html", html)


def build_zip():
    path = os.path.join(ROOT, "desperation-web.zip")
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        for rel in ZIP_CONTENTS:
            z.write(os.path.join(ROOT, rel), rel)
    return os.path.getsize(path)


if __name__ == "__main__":
    size_html = build_singlefile()
    print(f"Desperation-singlefile.html   {size_html:>8,} bytes")
    size_zip = build_zip()
    print(f"desperation-web.zip           {size_zip:>8,} bytes")
    print("\nBuild OK.")
